# -*- coding: utf-8 -*-
"""Exercise1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b6uIgWFQeJWYDgRLkWVt_XMypC-k48bn

#1. write a numpy program to create an elementwise comparison(greater,greater_equal,less,less_equal) of given two arrays.
"""

import numpy as np
x=np.array([1,6,3])
y=np.array([2,5,3])
print("Orginal Numbers")
print(x)
print(y)
print("\n 1. Comparison - Greater")
print(np.greater(x,y))
print("\n 2. Comparison - Greater_equal")
print(np.greater_equal(x,y))
print("\n 3. Comparison - Less")
print(np.less(x,y))
print("\n 4. Comparison - Less_equal")
print(np.less_equal(x,y))

"""#2.write a numpy program to create an array of all even integers from 30 to 70."""

import numpy as np
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array)

"""#3.write a numpy program to create a 3*3 identity matrix."""

import numpy as np
array_2D=np.identity(3)
print("3*3 matrix")
print(array_2D)

"""#4.write a numpy program to create a vector with values from 0 to 20 and change sign of the numbers in the range from 9 to 15."""

import numpy as np
x=np.arange(21)
print("\n orginal Vector:")
print(x)
print("\nAfter changing the sign of the numbers in the range from 9 to 15:")
x[(x>=9) & (x<=15)]*=-1
print(x)

"""#5.write a numpy program to create a 5*5 zero matrix with elements on the main diagonal equal to 1,2,3,4,5."""

import numpy as np
print("Matrix")
x=np.diag([1,2,3,4,5])
print(x)

"""6.write a numpy program to compute the sum of all the elements,sum of each column and sum of each row of a given array."""

import numpy as np
x=np.array([[0,1],[2,3]])
print("Orginal Array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x,axis=0))
print("Sum of each row:")
print(np.sum(x,axis=1))

"""7.write a numpy program to save a given array to a text file and load it."""

import numpy as np
import os
x=np.arange(12).reshape(4,3)
print("Orginal Array")
print(x)
header='col1 col2 col3'
np.savetxt('temp.txt',x,fmt="%d",header=header)
print("\nAfter loading, content of the text file:")
result=np.loadtxt('temp.txt')
print(result)

"""8.write a numpy program to check whether two arrays are equal(elementwise) or not."""

import numpy as np
nums1=np.array([0.5,1.5,0.2])
nums2=np.array([0.499999999,1.50000000001,0.2])
np.set_printoptions(precision=15)
print("Orginal Array")
print(nums1)
print(nums2)
print("\nTest said two arrays are equal or not!")
print(nums1==nums2)
nums1=np.array([0.5,1.5,0.23])
nums2=np.array([0.499999999,1.5,0.23])
np.set_printoptions(precision=15)
print("\nOrginal Array")
print(nums1)
print(nums2)
print("\nTest said two arrays are equal or not!")
print(nums1==nums2)

"""9.write a numpy program to create a 4*4 array with random values,now create a new array from the said array swapping first and last rows."""

import numpy as np
nums=np.arange(16,dtype='int').reshape(-1,4)
print("Orginal Array")
print(nums)
print("New array after swapping first an last rows of the said array")
new_nums=nums[[-1,1,2,0]]
print(new_nums)

"""10.write a numpy program to multiply two given arrays of same size element by element."""

import numpy as np
nums1=np.array([[2,5,2],[1,5,5]])
nums2=np.array([[5,3,4],[3,2,5]])
print("Array 1")
print(nums1)
print("Array 2")
print(nums2)
print("Multiply said arrays of same size element by element")
print(np.multiply(nums1,nums2))